require("myconfig.keybinds")
require("myconfig.options")
require("myconfig.colorscheme")
require("myconfig.mini")
require("myconfig.plugins")
require("myconfig.textobject")
require("myconfig.lsp")
require("myconfig.cmp")
