require("plugins.lsp")
require("plugins.cmp")
require("plugins.yazi")
require("plugins.session")

require("plugins.bufferline")
require("plugins.mini")
require("plugins.plugins")
require("plugins.textobject")
require("plugins.wilder")
require("plugins.pairs")
